# Generated by Django 5.0 on 2023-12-13 13:54

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='PeriodOfCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(verbose_name='Количество месяцев')),
            ],
            options={
                'verbose_name': 'Срок кредита',
                'verbose_name_plural': 'Сроки кредита',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='SumOfCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Сумма',
                'verbose_name_plural': 'Суммы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=255, unique=True, verbose_name='Номер телефона')),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True, verbose_name='Пароль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Логотип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Главная фотография')),
                ('average', models.CharField(max_length=255, null=True, verbose_name='Средний чек')),
                ('food_type', models.CharField(max_length=255, verbose_name='Тип еды')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('sales', models.ImageField(default=None, null=True, upload_to='', verbose_name='Акции')),
                ('prices', models.CharField(max_length=255, null=True, verbose_name='Цены для сертификата')),
                ('slug', models.SlugField(null=True, verbose_name='ссылка')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Адресс')),
                ('kitchen', models.CharField(max_length=255, null=True, verbose_name='Кухня')),
                ('novy', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('insta', models.CharField(max_length=255, null=True, verbose_name='Instagram')),
                ('whatsapp', models.CharField(max_length=255, null=True, verbose_name='Whatsapp')),
                ('work_hours', models.CharField(max_length=255, null=True, verbose_name='Часы работы')),
                ('menu', models.ManyToManyField(default=None, to='testapp.imagemodel', verbose_name='Меню')),
                ('period_of_credit', models.ManyToManyField(choices=[(3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], default=None, to='testapp.periodofcredit', verbose_name='Срок кредита')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.status', verbose_name='Статус')),
                ('sum_of_credit', models.ManyToManyField(default=None, to='testapp.sumofcredit', verbose_name='Сумма кредита')),
                ('tags', models.ManyToManyField(blank=True, default=None, to='testapp.tag', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.restaurant')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
