# Generated by Django 5.0 on 2023-12-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.AddField(
            model_name='order',
            name='period_of_credit',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='testapp.periodofcredit', verbose_name='Срок кредита'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Новые'), (2, 'Активированные'), (3, 'Отказы')], default=1, max_length=255, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_of_credit',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='testapp.sumofcredit', verbose_name='Сумма кредита'),
            preserve_default=False,
        ),
    ]
