# Generated by Django 5.0 on 2023-12-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_order_sum_order_period_of_credit_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=255, verbose_name='Дни недели')),
                ('hours', models.CharField(max_length=255, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Часы работы',
                'verbose_name_plural': 'Часы работы',
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='work_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.workhours', verbose_name='Часы работы'),
        ),
    ]
