# Generated by Django 5.0 on 2023-12-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_workhours_alter_restaurant_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='workhours',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='testapp.restaurant', verbose_name='Ресторан'),
            preserve_default=False,
        ),
    ]
