# Generated by Django 5.0 on 2023-12-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_restaurant_work_hours_workhours_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantimage',
            old_name='images',
            new_name='image',
        ),
    ]
