# Generated by Django 5.0 on 2023-12-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_restaurantimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='work_days_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Дни работы 1'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='work_days_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Дни работы 2'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='work_hours_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Часы работы 1'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='work_hours_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Часы работы 2'),
        ),
        migrations.DeleteModel(
            name='WorkHours',
        ),
    ]
