# Generated by Django 5.0 on 2023-12-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_restaurant_work_days_1_restaurant_work_days_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Меню'),
        ),
    ]
