# Generated by Django 5.0 on 2023-12-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_remove_restaurant_menu_delete_imagemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='period_of_credit',
            field=models.ManyToManyField(default=None, to='testapp.periodofcredit', verbose_name='Срок кредита'),
        ),
    ]
