# Generated by Django 4.1.5 on 2023-12-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_restaurant_period_of_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ManyToManyField(blank=True, default=None, to='testapp.restaurantimage', verbose_name='Фотографии'),
        ),
    ]
